services:
    app:
        extends:
            file: "./docker/dev/compose/app.yml"
            service: app
        build:
            context: .
            dockerfile: ./docker/dev/app/Dockerfile
        image: linkedin/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '3000:80'
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - linkedin

networks:
    linkedin:
        driver: bridge
